# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value
     pp5_movie_universe.movie_service.class: PP5\MovieUniverseBundle\Service\MovieService

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

     pp5_movie_universe.movie_service:
          class: %pp5_movie_universe.movie_service.class%
          arguments:
                - @=service('doctrine.orm.default_entity_manager').getRepository('PP5MovieUniverseBundle:Movie\\Movie')
