# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value
     pp5_movie_universe.movie_service.class: PP5\MovieUniverseBundle\Service\MovieService
     pp5_movie_universe.registration.form.type.class: PP5\MovieUniverseBundle\Form\Type\RegistrationFormType
     pp5_movie_universe.order_item.service.class: PP5\MovieUniverseBundle\Service\OrderItemService
     pp5_movie_universe.order.service.class: PP5\MovieUniverseBundle\Service\OrderService
     pp5_movie_universe.user.service.class: PP5\MovieUniverseBundle\Service\UserService
     pp5_movie_universe.payment.service.class: PP5\MovieUniverseBundle\Service\PaymentService
     pp5_movie_universe.before_controller.service.class: PP5\MovieUniverseBundle\Listener\BeforeControllerListener

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    pp5_movie_universe.movie_service:
        class: %pp5_movie_universe.movie_service.class%
        arguments:
            - @=service('doctrine.orm.default_entity_manager')

    pp5_movie_universe.registration.form.type:
        class: %pp5_movie_universe.registration.form.type.class%
        tags:
            - { name: form.type, alias: pp5_movie_universe_registration}

    pp5_movie_universe.order_item.service:
        class: %pp5_movie_universe.order_item.service.class%

    pp5_movie_universe.order.service:
        class: %pp5_movie_universe.order.service.class%
        arguments:
            - @=service('doctrine.orm.default_entity_manager')

    pp5_movie_universe.user.service:
        class: %pp5_movie_universe.user.service.class%
        arguments:
            - @=service('doctrine.orm.default_entity_manager')

    pp5_movie_universe.payment.service:
        class: %pp5_movie_universe.payment.service.class%
        arguments:
            - %dotpay_id%
            - %dotpay_pin%
            - @=service('doctrine.orm.default_entity_manager')
            - @pp5_movie_universe.order.service

    pp5_movie_universe.before_controller.service:
        class: %pp5_movie_universe.before_controller.service.class%
        arguments:
            - @security.context
        tags:
            - {name: kernel.event_listener, event: kernel.controller, method: onKernelController}