pp5_movie_universe:
    resource: "@PP5MovieUniverseBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

sylius_cart:
    resource: @SyliusCartBundle/Resources/config/routing.yml
    prefix: /cart